version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: p2p_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-net
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PORT=8080
      - ConnectionStrings__Default=Host=db;Port=5432;Database=p2p_db;Username=postgres;Password=postgres
    ports:
      - "8085:8080"
      - "8086:8081"
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge
