// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(P2PDbContext))]
    [Migration("20250908110459_auto_104_20250908110454")]
    partial class auto_104_20250908110454
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.DB.AccountEntity", b =>
                {
                    b.Property<string>("WalletAddress")
                        .HasColumnType("text")
                        .HasColumnName("wallet_address");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("LastActiveTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_time");

                    b.Property<int?>("OrdersCount")
                        .HasColumnType("integer")
                        .HasColumnName("orders_count");

                    b.Property<string>("Telegram")
                        .HasColumnType("text")
                        .HasColumnName("telegram");

                    b.Property<string>("TelegramId")
                        .HasColumnType("text")
                        .HasColumnName("telegram_chat_id");

                    b.HasKey("WalletAddress");

                    b.ToTable("account");
                });

            modelBuilder.Entity("Domain.Models.DB.AccountSwapHistoryEntity", b =>
                {
                    b.Property<string>("Tx")
                        .HasColumnType("text")
                        .HasColumnName("tx");

                    b.Property<decimal>("AmountIn")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("amount_in");

                    b.Property<decimal>("AmountOut")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("amount_out");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CryptoFrom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("crypto_from");

                    b.Property<string>("CryptoTo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("crypto_to");

                    b.Property<decimal>("PriceUsdIn")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("price_usd_in");

                    b.Property<decimal>("PriceUsdOut")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("price_usd_out");

                    b.Property<string>("UserWallet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_wallet");

                    b.HasKey("Tx");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_swap_created_at");

                    b.HasIndex("CryptoFrom", "CreatedAtUtc")
                        .HasDatabaseName("ix_swap_from_date");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CryptoFrom", "CreatedAtUtc"), new[] { "PriceUsdIn", "AmountIn", "Tx" });

                    b.HasIndex("CryptoTo", "CreatedAtUtc")
                        .HasDatabaseName("ix_swap_to_date");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CryptoTo", "CreatedAtUtc"), new[] { "PriceUsdOut", "AmountOut", "Tx" });

                    b.HasIndex("CryptoFrom", "PriceUsdIn", "CreatedAtUtc")
                        .HasDatabaseName("ix_swap_from_price_date");

                    b.HasIndex("CryptoTo", "PriceUsdOut", "CreatedAtUtc")
                        .HasDatabaseName("ix_swap_to_price_date");

                    b.ToTable("account_swap_history");
                });

            modelBuilder.Entity("Domain.Models.DB.AttachmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Bucket")
                        .HasColumnType("integer")
                        .HasColumnName("bucket");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("Immutable")
                        .HasColumnType("boolean")
                        .HasColumnName("immutable");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<DateTime?>("RetentionUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retention_until");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<DateTime?>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_attachment_storage_key");

                    b.HasIndex("MessageId", "CreatedAtUtc")
                        .HasDatabaseName("ix_attachment_msg_created");

                    b.HasIndex("Sha256", "SizeBytes")
                        .IsUnique()
                        .HasDatabaseName("ux_attachment_sha_size");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_attachment_status_created");

                    b.ToTable("attachments");
                });

            modelBuilder.Entity("Domain.Models.DB.ChildOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<string>("ContraAgentWallet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contra_agent_wallet");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("DealId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("deal_id");

                    b.Property<int>("EscrowStatus")
                        .HasColumnType("integer")
                        .HasColumnName("escrow_status");

                    b.Property<string>("FillNonce")
                        .HasColumnType("text")
                        .HasColumnName("fill_nonce");

                    b.Property<string>("FillPda")
                        .HasColumnType("text")
                        .HasColumnName("fill_pda");

                    b.Property<int?>("FilledAmount")
                        .HasColumnType("integer")
                        .HasColumnName("filled_amount");

                    b.Property<string>("OrderOwnerWallet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_owner_wallet");

                    b.Property<Guid>("ParentOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_order_id");

                    b.HasKey("Id");

                    b.HasIndex("DealId")
                        .HasDatabaseName("ix_child_order_deal");

                    b.HasIndex("ParentOrderId")
                        .HasDatabaseName("ix_child_order_parent");

                    b.HasIndex("EscrowStatus", "CreatedAtUtc")
                        .HasDatabaseName("ix_child_order_status_created");

                    b.ToTable("child_order");
                });

            modelBuilder.Entity("Domain.Models.DB.CoinJellyAccountHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountGet")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("amount_get");

                    b.Property<decimal>("AmountSend")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("amount_send");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("CryptoGet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("crypto_get");

                    b.Property<string>("CryptoGetChain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("crypto_get_chain");

                    b.Property<string>("CryptoSend")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("crypto_send");

                    b.Property<decimal>("FeeAtomic")
                        .HasColumnType("numeric(78,0)")
                        .HasColumnName("fee_atomic");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TxID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tx_id");

                    b.Property<string>("UserWallet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_wallet");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_cj_hist_created_at");

                    b.HasIndex("TxID")
                        .HasDatabaseName("ix_cj_hist_txid");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_cj_hist_status_date");

                    b.ToTable("coin_jelly_account_history_entity");
                });

            modelBuilder.Entity("Domain.Models.DB.CoinJellyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyWalletAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_wallet_address");

                    b.Property<string>("CryptoCurrencyChain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("crypto_currency_chain");

                    b.Property<string>("CryptoCurrencyCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("crypto_currency_code");

                    b.Property<string>("CryptoCurrencyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("crypto_currency_name");

                    b.HasKey("Id");

                    b.HasIndex("CryptoCurrencyName", "CryptoCurrencyChain")
                        .IsUnique()
                        .HasDatabaseName("ux_coin_jelly_currency_chain");

                    b.ToTable("coin_jelly");
                });

            modelBuilder.Entity("Domain.Models.DB.CoinPrice.AppLockEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid?>("LockOwner")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_owner");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_utc");

                    b.HasKey("Name");

                    b.HasIndex("LockedUntilUtc");

                    b.ToTable("app_lock");
                });

            modelBuilder.Entity("Domain.Models.DB.CoinPrice.PriceSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CollectedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime>("MinuteBucketUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("minute_bucket_utc");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("price");

                    b.Property<string>("TokenMint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_mint");

                    b.HasKey("Id");

                    b.HasIndex("MinuteBucketUtc")
                        .HasDatabaseName("ix_price_minute_bucket");

                    b.HasIndex("TokenMint", "MinuteBucketUtc")
                        .IsUnique()
                        .HasDatabaseName("ux_price_minute");

                    b.HasIndex(new[] { "MinuteBucketUtc" }, "ix_price_minute_bucket");

                    b.HasIndex(new[] { "TokenMint", "MinuteBucketUtc" }, "ux_price_minute")
                        .IsUnique();

                    b.ToTable("price_snapshot_minute", (string)null);
                });

            modelBuilder.Entity("Domain.Models.DB.CoinPrice.TokenEntity", b =>
                {
                    b.Property<string>("Mint")
                        .HasColumnType("text")
                        .HasColumnName("mint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int?>("Decimals")
                        .HasColumnType("integer")
                        .HasColumnName("decimals");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.HasKey("Mint");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("ix_token_verified");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("ix_token_symbol");

                    b.ToTable("token", (string)null);
                });

            modelBuilder.Entity("Domain.Models.DB.Currency.Currency", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("currency_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("currency");
                });

            modelBuilder.Entity("Domain.Models.DB.EscrowOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("AdminCall")
                        .HasColumnType("boolean")
                        .HasColumnName("admin_call");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("amount");

                    b.Property<string>("AutoReply")
                        .HasColumnType("text")
                        .HasColumnName("auto_reply");

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("base_price");

                    b.Property<string>("BuyerFiat")
                        .HasColumnType("text")
                        .HasColumnName("buyer_fiat");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<decimal>("DealId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("deal_id");

                    b.Property<string>("EscrowPda")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("escrow_pda");

                    b.Property<int>("EscrowStatus")
                        .HasColumnType("integer")
                        .HasColumnName("escrow_status");

                    b.Property<string>("FiatCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fiat_code");

                    b.Property<decimal>("FilledQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("filled_quantity");

                    b.Property<bool>("IsPartial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_partial");

                    b.Property<int>("ListingMode")
                        .HasColumnType("integer")
                        .HasColumnName("listing_mode");

                    b.Property<decimal?>("MarginPercent")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("margin_percent");

                    b.Property<decimal>("MaxFiatAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("max_fiat_amount");

                    b.Property<int?>("MinAccountAgeDays")
                        .HasColumnType("integer")
                        .HasColumnName("min_account_age_days");

                    b.Property<decimal>("MinFiatAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("min_fiat_amount");

                    b.Property<byte>("OfferSide")
                        .HasColumnType("smallint")
                        .HasColumnName("offer_side");

                    b.Property<int?>("PaymentWindowMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("payment_window_minutes");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("price");

                    b.Property<int>("PriceType")
                        .HasColumnType("integer")
                        .HasColumnName("price_type");

                    b.Property<string>("ReferralCode")
                        .HasColumnType("text")
                        .HasColumnName("referral_code");

                    b.Property<string>("SellerCrypto")
                        .HasColumnType("text")
                        .HasColumnName("seller_crypto");

                    b.PrimitiveCollection<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Terms")
                        .HasColumnType("text")
                        .HasColumnName("terms");

                    b.Property<string>("TokenMint")
                        .HasColumnType("text")
                        .HasColumnName("token_mint");

                    b.PrimitiveCollection<string[]>("VisibleInCountries")
                        .HasColumnType("text[]")
                        .HasColumnName("visible_countries");

                    b.HasKey("Id");

                    b.HasIndex("TokenMint", "FiatCode", "OfferSide", "EscrowStatus", "Price")
                        .HasDatabaseName("ix_escrow_best_price");

                    b.ToTable("escrow_orders");
                });

            modelBuilder.Entity("Domain.Models.DB.EscrowOrderPaymentMethodEntity", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<short>("MethodId")
                        .HasColumnType("smallint")
                        .HasColumnName("method_id");

                    b.HasKey("OrderId", "MethodId");

                    b.HasIndex("MethodId", "OrderId");

                    b.ToTable("escrow_order_payment_methods");
                });

            modelBuilder.Entity("Domain.Models.DB.MessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<decimal>("RoomDealId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RoomDealId", "CreatedAtUtc");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("Domain.Models.DB.Metrics.AggregatorState", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTime>("Value")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("aggregator_state");
                });

            modelBuilder.Entity("Domain.Models.DB.Metrics.AssetVolumeDailyEntity", b =>
                {
                    b.Property<DateTime>("Day")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("day");

                    b.Property<string>("TokenMint")
                        .HasColumnType("text")
                        .HasColumnName("token_mint");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("volume");

                    b.HasKey("Day", "TokenMint");

                    b.ToTable("asset_volume_daily");
                });

            modelBuilder.Entity("Domain.Models.DB.Metrics.BanEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("Until")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("until");

                    b.Property<string>("Wallet")
                        .HasColumnType("text")
                        .HasColumnName("wallet");

                    b.HasKey("Id");

                    b.ToTable("bans");
                });

            modelBuilder.Entity("Domain.Models.DB.Metrics.DealTimeDailyEntity", b =>
                {
                    b.Property<DateTime>("Day")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenMint")
                        .HasColumnType("text");

                    b.Property<double>("AvgSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("TradeCnt")
                        .HasColumnType("integer");

                    b.HasKey("Day", "TokenMint");

                    b.ToTable("deal_time_daily");
                });

            modelBuilder.Entity("Domain.Models.DB.Metrics.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("event_type");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.Property<string>("Wallet")
                        .HasColumnType("text")
                        .HasColumnName("wallet");

                    b.HasKey("Id");

                    b.ToTable("events");
                });

            modelBuilder.Entity("Domain.Models.DB.Metrics.FunnelMetricsDailyEntity", b =>
                {
                    b.Property<DateTime>("Day")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("day");

                    b.Property<int>("ConnectsCnt")
                        .HasColumnType("integer")
                        .HasColumnName("connects_cnt");

                    b.Property<int>("OrdersCnt")
                        .HasColumnType("integer")
                        .HasColumnName("orders_cnt");

                    b.Property<int>("TradesCnt")
                        .HasColumnType("integer")
                        .HasColumnName("trades_cnt");

                    b.HasKey("Day");

                    b.ToTable("funnel_metrics_daily");
                });

            modelBuilder.Entity("Domain.Models.DB.Metrics.OrderCreatedDailyEntity", b =>
                {
                    b.Property<DateTime>("Day")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("day");

                    b.Property<byte>("Side")
                        .HasColumnType("smallint")
                        .HasColumnName("side");

                    b.Property<int>("CreatedCnt")
                        .HasColumnType("integer")
                        .HasColumnName("created_cnt");

                    b.HasKey("Day", "Side");

                    b.HasIndex("Day");

                    b.HasIndex("Side");

                    b.ToTable("order_created_daily");
                });

            modelBuilder.Entity("Domain.Models.DB.Metrics.OrderStatusDailyEntity", b =>
                {
                    b.Property<DateTime>("Day")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("day");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Cnt")
                        .HasColumnType("integer")
                        .HasColumnName("cnt");

                    b.HasKey("Day", "Status");

                    b.ToTable("order_status_daily");
                });

            modelBuilder.Entity("Domain.Models.DB.Metrics.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("outbox_messages");
                });

            modelBuilder.Entity("Domain.Models.DB.Metrics.RatingReviewEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal?>("DealId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("deal_id");

                    b.Property<string>("FromWallet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_wallet");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("score");

                    b.Property<string>("ToWallet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_wallet");

                    b.HasKey("Id");

                    b.ToTable("rating_reviews");
                });

            modelBuilder.Entity("Domain.Models.DB.Metrics.SessionEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Wallet")
                        .HasColumnType("text")
                        .HasColumnName("wallet");

                    b.HasKey("SessionId");

                    b.HasIndex("LastSeenAt");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("Domain.Models.DB.Metrics.TvlSnapshotEntity", b =>
                {
                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at");

                    b.Property<string>("TokenMint")
                        .HasColumnType("text")
                        .HasColumnName("token_mint");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("balance");

                    b.HasKey("TakenAt", "TokenMint");

                    b.ToTable("tvl_snapshots");
                });

            modelBuilder.Entity("Domain.Models.DB.Metrics.TxHistoryEntity", b =>
                {
                    b.Property<string>("TxHash")
                        .HasColumnType("text")
                        .HasColumnName("tx_hash");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(38,0)")
                        .HasColumnName("amount");

                    b.Property<string>("Counterparty")
                        .HasColumnType("text")
                        .HasColumnName("counterparty_wallet");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("side");

                    b.Property<string>("TokenMint")
                        .HasColumnType("text")
                        .HasColumnName("token_mint");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.Property<string>("Wallet")
                        .HasColumnType("text")
                        .HasColumnName("wallet");

                    b.HasKey("TxHash");

                    b.ToTable("tx_history");
                });

            modelBuilder.Entity("Domain.Models.DB.Metrics.UserMetricsDailyEntity", b =>
                {
                    b.Property<DateTime>("Day")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("day");

                    b.Property<int>("DauIps")
                        .HasColumnType("integer")
                        .HasColumnName("dau_ips");

                    b.Property<int>("DauUsers")
                        .HasColumnType("integer")
                        .HasColumnName("dau_users");

                    b.Property<int>("MauUsers")
                        .HasColumnType("integer")
                        .HasColumnName("mau_users");

                    b.Property<int>("WauUsers")
                        .HasColumnType("integer")
                        .HasColumnName("wau_users");

                    b.HasKey("Day");

                    b.ToTable("user_metrics_daily");
                });

            modelBuilder.Entity("Domain.Models.DB.PaymentMethod.PaymentCategory", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("payment_categories");
                });

            modelBuilder.Entity("Domain.Models.DB.PaymentMethod.PaymentMethod", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("method_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("payment_methods");
                });

            modelBuilder.Entity("Domain.Models.DB.PaymentMethod.PaymentPopularityDaily", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<short>("MethodId")
                        .HasColumnType("smallint")
                        .HasColumnName("method_id");

                    b.Property<string>("Region")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("region");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("cnt");

                    b.HasKey("Day", "MethodId", "Region");

                    b.HasIndex("Region", "Day", "Count");

                    b.ToTable("payment_popularity_daily");
                });

            modelBuilder.Entity("Domain.Models.DB.RefreshTokenEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("RefreshHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_hash");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("ua");

                    b.Property<string>("Wallet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wallet");

                    b.HasKey("Id");

                    b.ToTable("auth_refresh");
                });

            modelBuilder.Entity("Domain.Models.DB.RoomEntity", b =>
                {
                    b.Property<decimal>("DealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("deal_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime>("LastMessageTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_time")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("DealId");

                    b.HasIndex("DealId")
                        .IsUnique();

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("Domain.Models.DB.TelegramLinkEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("ExpiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC' + INTERVAL '1 day'");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wallet_address");

                    b.HasKey("Code");

                    b.ToTable("telegram_link");
                });

            modelBuilder.Entity("Domain.Models.DB.AttachmentEntity", b =>
                {
                    b.HasOne("Domain.Models.DB.MessageEntity", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Domain.Models.DB.ChildOrderEntity", b =>
                {
                    b.HasOne("Domain.Models.DB.EscrowOrderEntity", "ParentOrder")
                        .WithMany("ChildOrders")
                        .HasForeignKey("ParentOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentOrder");
                });

            modelBuilder.Entity("Domain.Models.DB.EscrowOrderPaymentMethodEntity", b =>
                {
                    b.HasOne("Domain.Models.DB.PaymentMethod.PaymentMethod", "Method")
                        .WithMany()
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.DB.EscrowOrderEntity", "Order")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Models.DB.MessageEntity", b =>
                {
                    b.HasOne("Domain.Models.DB.AccountEntity", "Account")
                        .WithMany("Messages")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.DB.RoomEntity", "Room")
                        .WithMany("Messages")
                        .HasForeignKey("RoomDealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Domain.Models.DB.PaymentMethod.PaymentMethod", b =>
                {
                    b.HasOne("Domain.Models.DB.PaymentMethod.PaymentCategory", "Category")
                        .WithMany("Methods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Models.DB.AccountEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Domain.Models.DB.EscrowOrderEntity", b =>
                {
                    b.Navigation("ChildOrders");

                    b.Navigation("PaymentMethods");
                });

            modelBuilder.Entity("Domain.Models.DB.MessageEntity", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Domain.Models.DB.PaymentMethod.PaymentCategory", b =>
                {
                    b.Navigation("Methods");
                });

            modelBuilder.Entity("Domain.Models.DB.RoomEntity", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
