// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(P2PDbContext))]
    [Migration("20250604141035_mgr_f_q")]
    partial class mgr_f_q
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.DB.EscrowOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("amount");

                    b.Property<string>("BuyerFiat")
                        .HasColumnType("text")
                        .HasColumnName("buyer_fiat");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<decimal>("DealId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("deal_id");

                    b.Property<string>("EscrowPda")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("escrow_pda");

                    b.Property<string>("FiatCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fiat_code");

                    b.Property<decimal>("FilledQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("filled_quantity");

                    b.Property<decimal>("MaxFiatAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("max_fiat_amount");

                    b.Property<decimal>("MinFiatAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("min_fiat_amount");

                    b.Property<byte>("OfferSide")
                        .HasColumnType("smallint")
                        .HasColumnName("offer_side");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("price");

                    b.Property<string>("SellerCrypto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seller_crypto");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TokenMint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_mint");

                    b.HasKey("Id");

                    b.ToTable("escrow_orders");
                });
#pragma warning restore 612, 618
        }
    }
}
