name: Deploy Back

on:
  push:
    branches: [ master ]

jobs:
  deploy-back:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Deploy back via SSH
      uses: appleboy/ssh-action@v1
      with:
        host:     ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key:      ${{ secrets.SSH_PRIVATE_KEY }}
        port:     ${{ secrets.SSH_PORT }}
        script: |
          mkdir -p ${{ secrets.BACK_DIR }}
          bash ${{ secrets.BACK_SCRIPT }} ${{ secrets.BACK_DIR }}
