name: Deploy Backend (ssh → build on server)

on:
  push:
    branches: [ master ]

permissions:
  contents: write

env:
  HOST: 65.109.86.205
  USER: p2p_user
  TARGET_DIR: /opt/p2p_back/src
  DEPLOY_SCRIPT: /usr/local/bin/deploy_p2p_back.sh

  EF_PROJECT: Infrastructure/Infrastructure.csproj
  STARTUP_PROJECT: Aswap-back/Aswap-back.csproj
  DB_CONTEXT: P2PDbContext

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x   # ← став ту версію, на якій реально таргетиться проект

    # Перевірка шляхів + список DbContext
    - name: Verify EF paths
      shell: bash
      run: |
        echo "EF_PROJECT=$EF_PROJECT"
        echo "STARTUP_PROJECT=$STARTUP_PROJECT"
        test -f "$EF_PROJECT" || (echo "❌ EF_PROJECT not found"; ls -laR; exit 1)
        test -f "$STARTUP_PROJECT" || (echo "❌ STARTUP_PROJECT not found"; ls -laR; exit 1)

        dotnet restore
        dotnet tool update --global dotnet-ef
        export PATH="$HOME/.dotnet/tools:$PATH"

        dotnet ef dbcontext list \
          --project "$EF_PROJECT" \
          --startup-project "$STARTUP_PROJECT"

    # (опц.) автогенерація міграції — БЕЗ затирання PATH
    - name: Generate EF migration if model changed
      shell: bash
      run: |
        set -e
        export PATH="$HOME/.dotnet/tools:$PATH"

        MIG_NAME="auto_${GITHUB_RUN_NUMBER}_$(/usr/bin/date +%Y%m%d%H%M%S)"

        set +e
        dotnet ef migrations add "$MIG_NAME" \
          --project "$EF_PROJECT" \
          --startup-project "$STARTUP_PROJECT" \
          --context "$DB_CONTEXT"
        STATUS=$?
        set -e

        if git status --porcelain | grep -E '^ M|^A |^\?\?' | grep 'Migrations/'; then
          echo "Detected new migration files. Committing..."
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "ci: auto EF migration $MIG_NAME [skip ci]"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
        else
          echo "No model changes — skipping commit."
        fi

    # SSH ключ
    - name: Add SSH key
      shell: bash
      run: |
        mkdir -p ~/.ssh && chmod 700 ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

    # rsync коду
    - name: Sync backend to server
      shell: bash
      run: |
        ssh $USER@$HOST "mkdir -p $TARGET_DIR"
        rsync -az --delete \
          --exclude=".git" \
          --exclude=".github" \
          ./ $USER@$HOST:$TARGET_DIR/

    # build+restart (деплой-скрипт на сервері робить усе інше; міграції застосуються на старті або бандлом — як налаштовано)
    - name: Build & run backend container
      shell: bash
      run: ssh $USER@$HOST "sudo $DEPLOY_SCRIPT"
