name: Deploy Back

on:
  push:
    branches: [ master ]        # міняйте, якщо треба

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    steps:
      - name: SSH & run deploy script
        uses: appleboy/ssh-action@v1
        with:
          host:     ${{ secrets.HOST }}
          username: ${{ secrets.USER }}      # p2p_user
          key:      ${{ secrets.SSH_PRIVATE_KEY }}       # приватний ключ
          port:     22      # 22 якщо стандарт
          script: |
            set -e
            echo "== Deploy $(date)"
            bash /opt/p2p_back/scripts/deploy_p2p_back.sh main
